import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Czzzz",
    description: "Generated by create next app",
};

export default function page() {
    return (
        <div>
            page 
        </div>
    )
}
